
server:
    port: 8084
spring:
    data:
        mongodb:
            database: dbproyecto01
            host: localhost
            
application:
    endpoints:
        url:
            valid_address: http://localhost:8081/api/